<h1 style="text-align: center;">Pagina de listar</h1>
<hr>
<table style="text-align: center;" class="container table table-striped table-hover">
    <thead class="table-dark">
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Matricula</th>
            <th>Cidade</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($dados as $linha) {
            $id = $linha['id'];
            echo 
                "<tr>
                    <td>{$linha['id']}</td>
                    <td>{$linha['nome']}</td>
                    <td>{$linha['matricula']}</td>
                    <td>{$linha['cidade']}</td>
                    <td>
                        <a href='/editar?id={$id}' class='btn btn-outline-warning'>Editar</a>
                        <button type='button' class='btn btn-danger' data-bs-toggle='modal' data-bs-target='#modalexcluir' onclick='pegarID({$id})'>Excluir</button>
                    </td>
                </tr>";
        }
        ?>
    </tbody>
</table>
<div class='modal fade' id='modalexcluir' tabindex='-1' aria-labelledby='exampleModalLabel' aria-hidden='true'>
    <div class='modal-dialog'>
        <div class='modal-content'>
            <div class='modal-header'>
                <h1 class='modal-title fs-5' id='exampleModalLabel'>APAGAR ALUNO</h1>
                <button type='button' class='btn-close' data-bs-dismiss='modal' aria-label='Close'></button>
            </div>
            <div class='modal-body'>
                DESEJA APAGAR ESTE ALUNO?
                <input type="hidden" id="idatual">
            </div>
            <div class='modal-footer'>
                <button type='button' class='btn btn-secondary' data-bs-dismiss='modal'>Cancelar</button>
                <button type='button' onclick='confirmar()' class='btn btn-danger'>Confirmar</button>
            </div>
        </div>
    </div>
</div>
<script>
    function pegarID(id){
        document.getElementById("idatual").value = id;
    }
    function confirmar(){
        if(true === confirm('Tem certeza?')){
            id= idatual.value;
            location.href = '/excluir?id='+id;
        }
    }
</script>