<h1 style="text-align: center">Novo</h1>
<hr>

<form action="#" method="POST">
    <div class="form-group m-2">
        <label for="nome">Nome</label>
        <input value="<?php echo $_POST['nome'] ?? '' ?>" required pattern="(?=.*[A-Z])(?=.*[a-z]){3,}" class="form-control" id="nome" type="text" name="nome">
    </div>
    <div class="form-group m-2">
        <label for="matricula">Matricula</label>
        <input value="<?php echo $_POST['matricula'] ?? '' ?>" required pattern="([0-9]){3,}" class="form-control" id="matricula" type="text" name="matricula">
    </div>
    <div class="form-group m-2">
        <label for="cidade">Cidade</label>
        <input value="<?php echo $_POST['cidade'] ?? '' ?>" required pattern="(?=.*[A-Z])(?=.*[a-z]){3,}" class="form-control" id="cidade" type="text" name="cidade">
    </div>
    <button class="btn btn-success" type="submit" value="criar" name="criar">Cadastrar</button>
</form>